global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'web-admin'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['web-admin:3001']

#   - job_name: 'web-client'
#     metrics_path: '/api/metrics'
#     static_configs:
#       - targets: ['web-client:3000']
